apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: andreas-tester-nais
  namespace: andreas-tester-nais
spec:
  ingresses:
    - https://andreas-tester-nais.sandbox.test-nais.cloud.nais.io
  image: {{image}}
  port: 8080
  ttl: 3h
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 32Mi